import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class PertambahanDuaAngkaGUI extends javax.swing.JFrame {

    /**
     * Creates new form PertambahanDuaAngkaGUI
     */
    public PertambahanDuaAngkaGUI() {
        initComponents();
    }

    private void filterKeyTyped(java.awt.event.KeyEvent evt) {
        char filter = evt.getKeyChar();
        if(!(Character.isDigit(filter)||(filter==KeyEvent.VK_BACKSPACE)||(filter==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "Masukkan Hanya Angka ! ");
            evt.consume();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AngkaPertamaLabel = new javax.swing.JLabel();
        AngkaPertamaTF = new javax.swing.JTextField();
        AngkaKeduaLabel = new javax.swing.JLabel();
        AngkaKeduaTF = new javax.swing.JTextField();
        operatorLabel = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        HasilLabel = new javax.swing.JLabel();
        textHasil = new javax.swing.JTextField();
        BTTambah = new javax.swing.JButton();
        BTHapus = new javax.swing.JButton();
        BTKeluar = new javax.swing.JButton();
        BTkurang = new javax.swing.JButton();
        BTKali = new javax.swing.JButton();
        BTBagi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panji Sukma Putra Samudra 17630046", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 255, 0));

        AngkaPertamaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AngkaPertamaLabel.setText("Angka Pertama");

        AngkaPertamaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AngkaPertamaTFKeyTyped(evt);
            }
        });

        AngkaKeduaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AngkaKeduaLabel.setText("Angka Kedua");

        AngkaKeduaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AngkaKeduaTFKeyTyped(evt);
            }
        });

        operatorLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AngkaKeduaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AngkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AngkaPertamaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AngkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AngkaPertamaLabel)
                            .addComponent(AngkaPertamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AngkaKeduaLabel)
                            .addComponent(AngkaKeduaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(operatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        HasilLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HasilLabel.setText("Hasil");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(HasilLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HasilLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        BTTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTTambah.setText("TAMBAH");
        BTTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTambahActionPerformed(evt);
            }
        });

        BTHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTHapus.setText("HAPUS");
        BTHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTHapusActionPerformed(evt);
            }
        });

        BTKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTKeluar.setText("KELUAR");
        BTKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTKeluarActionPerformed(evt);
            }
        });

        BTkurang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTkurang.setText("KURANG");
        BTkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTkurangActionPerformed(evt);
            }
        });

        BTKali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTKali.setText("KALI");
        BTKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTKaliActionPerformed(evt);
            }
        });

        BTBagi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTBagi.setText("BAGI");
        BTBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBagiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTKali, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTTambah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTkurang))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(BTBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTKeluar))
                        .addGap(19, 19, 19)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTTambah)
                    .addComponent(BTkurang)
                    .addComponent(BTHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTKali)
                    .addComponent(BTBagi)
                    .addComponent(BTKeluar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTambahActionPerformed
        if(AngkaPertamaTF.getText().equals("") || AngkaKeduaTF.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Salah satu input tidak boleh kosong");
    }else{
       operatorLabel.setText("+");
       int AngkaPertama = Integer.valueOf(AngkaPertamaTF.getText());
       int AngkaKedua = Integer.valueOf(AngkaKeduaTF.getText());
       int hasil = AngkaPertama + AngkaKedua;
       textHasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BTTambahActionPerformed
    
  }
    private void BTHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTHapusActionPerformed
        if(AngkaPertamaTF.getText().equals("") || AngkaKeduaTF.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"TIDAK ADA YANG DIHAPUS");
    }else{
        AngkaPertamaTF.setText("");
        AngkaKeduaTF.setText(null);
        textHasil.setText("");
        operatorLabel.setText("");
        AngkaPertamaTF.requestFocus();
    }//GEN-LAST:event_BTHapusActionPerformed
}
    private void BTKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTKeluarActionPerformed
        int exit = JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION){
        System.exit(0);
    }//GEN-LAST:event_BTKeluarActionPerformed
 }
    private void BTkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTkurangActionPerformed
        if(AngkaPertamaTF.getText().equals("") || AngkaKeduaTF.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Salah satu input tidak boleh kosong");
    }else{
        operatorLabel.setText("-");
        int AngkaPertama = Integer.valueOf(AngkaPertamaTF.getText());
       int AngkaKedua = Integer.valueOf(AngkaKeduaTF.getText());
       int hasil = AngkaPertama - AngkaKedua;
       textHasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BTkurangActionPerformed
}
    private void BTKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTKaliActionPerformed
       if(AngkaPertamaTF.getText().equals("") || AngkaKeduaTF.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Salah satu input tidak boleh kosong");
    }else{
        operatorLabel.setText("X");
       int AngkaPertama = Integer.valueOf(AngkaPertamaTF.getText());
       int AngkaKedua = Integer.valueOf(AngkaKeduaTF.getText());
       int hasil = AngkaPertama * AngkaKedua;
       textHasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BTKaliActionPerformed
}
    private void BTBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBagiActionPerformed
       if(AngkaPertamaTF.getText().equals("") || AngkaKeduaTF.getText().equals("")) {
        JOptionPane.showMessageDialog(null,"Salah satu input tidak boleh kosong");
    }else{
        operatorLabel.setText("/");
        int AngkaPertama = Integer.valueOf(AngkaPertamaTF.getText());
       int AngkaKedua = Integer.valueOf(AngkaKeduaTF.getText());
       int hasil = AngkaPertama / AngkaKedua;
       textHasil.setText(Integer.toString(hasil));
    }//GEN-LAST:event_BTBagiActionPerformed
}
    private void operatorLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operatorLabelActionPerformed

    private void AngkaPertamaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AngkaPertamaTFKeyTyped
        filterKeyTyped(evt);
    }//GEN-LAST:event_AngkaPertamaTFKeyTyped

    private void AngkaKeduaTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AngkaKeduaTFKeyTyped
        filterKeyTyped(evt);
    }//GEN-LAST:event_AngkaKeduaTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PertambahanDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PertambahanDuaAngkaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AngkaKeduaLabel;
    private javax.swing.JTextField AngkaKeduaTF;
    private javax.swing.JLabel AngkaPertamaLabel;
    private javax.swing.JTextField AngkaPertamaTF;
    private javax.swing.JButton BTBagi;
    private javax.swing.JButton BTHapus;
    private javax.swing.JButton BTKali;
    private javax.swing.JButton BTKeluar;
    private javax.swing.JButton BTTambah;
    private javax.swing.JButton BTkurang;
    private javax.swing.JLabel HasilLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField operatorLabel;
    private javax.swing.JTextField textHasil;
    // End of variables declaration//GEN-END:variables
}
